# Generated by Django 3.2.8 on 2021-11-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin',
            old_name='longitutde',
            new_name='longitude',
        ),
    ]
