# Generated by Django 3.2.8 on 2021-11-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_rename_longitutde_bin_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='collection_frequency',
            field=models.IntegerField(),
        ),
    ]
